name: f5-tts
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.15=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.0
      - accelerate==1.1.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.7.0
      - async-timeout==5.0.1
      - attrs==24.2.0
      - audioread==3.0.1
      - av==14.0.1
      - biopython==1.79
      - bitsandbytes==0.45.0
      - boto3==1.35.76
      - botocore==1.35.76
      - cached-path==1.6.4
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - ctranslate2==4.5.0
      - cycler==0.12.1
      - cython==3.0.11
      - dataclassy==1.0.1
      - datasets==3.1.0
      - decorator==5.1.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - einops==0.8.0
      - einx==0.3.0
      - ema-pytorch==0.7.7
      - encodec==0.1.1
      - exceptiongroup==1.2.2
      - f5-tts==0.1.1
      - fastapi==0.115.6
      - fastdtw==0.3.4
      - faster-whisper==1.1.0
      - ffmpy==0.4.0
      - filelock==3.13.4
      - flatbuffers==24.3.25
      - fonttools==4.55.2
      - frozendict==2.4.6
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.23.0
      - google-auth==2.36.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - gradio==5.8.0
      - gradio-client==1.5.1
      - greenlet==3.1.1
      - grpcio==1.71.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.26.3
      - humanfriendly==10.0
      - idna==3.10
      - jieba==0.42.1
      - jinja2==3.1.4
      - jiwer==3.0.5
      - jmespath==1.0.1
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - kneed==0.8.5
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - loguru==0.7.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.3
      - mdurl==0.1.2
      - montreal-forced-aligner==3.2.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - nnmnkwii==0.1.3
      - num2words==0.5.13
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - onnxruntime==1.20.1
      - orjson==3.10.12
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.0.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - praatio==6.2.0
      - propcache==0.2.1
      - proto-plus==1.25.0
      - protobuf==5.29.1
      - psutil==6.1.0
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pymcd==0.2.1
      - pyparsing==3.2.0
      - pypinyin==0.53.0
      - pysptk==1.0.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.19
      - pytz==2024.2
      - pyworld==0.3.4
      - pyyaml==6.0.2
      - rapidfuzz==3.10.1
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rich-click==1.8.5
      - rsa==4.9
      - ruff==0.8.2
      - s3transfer==0.10.4
      - safehttpx==0.1.6
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - sqlalchemy==2.0.36
      - starlette==0.41.3
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - tomlkit==0.13.2
      - torch==2.3.0+cu118
      - torchaudio==2.3.0+cu118
      - torchdiffeq==0.2.5
      - tqdm==4.67.1
      - transformers==4.47.0
      - transformers-stream-generator==0.0.5
      - triton==2.3.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - uvicorn==0.32.1
      - vocos==0.1.0
      - wandb==0.19.0
      - websockets==14.1
      - werkzeug==3.1.3
      - x-transformers==1.42.24
      - xxhash==3.5.0
      - yarl==1.18.3
      - modelscope==1.33.0
